import { FOLIO_THEMES } from '../../shared/theme';

export const BACKUP_FILE_NAME = 'folio-data.json';
export const BACKUP_SCHEMA_FILE_NAME = 'folio-data.schema.json';

export const BACKUP_JSON_SCHEMA: Record<string, unknown> = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  title: 'Folio Backup Data',
  description:
    'Schema for folio-data.json generated by Folio Chrome extension.',
  type: 'object',
  required: ['items', 'tags', 'settings', 'meta'],
  properties: {
    items: {
      type: 'object',
      additionalProperties: { $ref: '#/$defs/item' }
    },
    tags: {
      type: 'array',
      items: { type: 'string' }
    },
    settings: {
      $ref: '#/$defs/settings'
    },
    meta: {
      type: 'object',
      required: ['version', 'createdAt'],
      properties: {
        version: { type: 'string' },
        createdAt: { type: 'number' }
      },
      additionalProperties: true
    }
  },
  $defs: {
    item: {
      type: 'object',
      required: [
        'id',
        'url',
        'title',
        'favicon',
        'domain',
        'status',
        'tags',
        'note',
        'createdAt',
        'updatedAt',
        'lastOpenedAt'
      ],
      properties: {
        id: { type: 'string' },
        url: { type: 'string' },
        title: { type: 'string' },
        favicon: { type: 'string' },
        domain: { type: 'string' },
        status: { enum: ['unread', 'reading', 'done'] },
        tags: {
          type: 'array',
          items: { type: 'string' }
        },
        note: { type: 'string' },
        createdAt: { type: 'number' },
        updatedAt: { type: 'number' },
        lastOpenedAt: { type: ['number', 'null'] }
      },
      additionalProperties: true
    },
    settings: {
      type: 'object',
      required: [
        'locale',
        'iconVariant',
        'theme',
        'defaultStatus',
        'sortMode',
        'syncDirectory',
        'lastSyncedAt',
        'lastSyncError'
      ],
      properties: {
        locale: { enum: ['en', 'zh-CN'] },
        iconVariant: { enum: ['classic', 'mono'] },
        theme: { enum: FOLIO_THEMES },
        defaultStatus: { enum: ['unread', 'reading'] },
        sortMode: {
          enum: ['saved_desc', 'saved_asc', 'domain_asc', 'title_asc', 'status']
        },
        syncDirectory: { type: ['string', 'null'] },
        lastSyncedAt: { type: ['number', 'null'] },
        lastSyncError: { type: ['string', 'null'] }
      },
      additionalProperties: true
    }
  },
  additionalProperties: true
};

export interface BackupWriteSuccess {
  ok: true;
  syncedAt: number;
}

export interface BackupWriteFailure {
  ok: false;
  error: string;
}

export type BackupWriteResult = BackupWriteSuccess | BackupWriteFailure;
